baseURL = "https://www.leventhalmap.org"
description = "The LMEC uses maps and geography to explore the connections between people and places in Boston, New England, and beyond."
locale = "en_US"
theme = "neatline"
title = "Leventhal Map & Education Center at the Boston Public Library"
metaDataFormat = "yaml"
[taxonomies]
author = "author"
tag = "tags"
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
attribute = true
autoHeadingID = true
autoHeadingIDType = "github"
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false
[[menu.footer]]
URL = "privacy"
name = "Privacy Policy"
weight = 8
[[menu.footer]]
URL = "accessibility"
name = "Accessibility"
weight = 7
[[menu.footer]]
URL = "/about/mission-history"
name = "Mission & History"
weight = 6
[[menu.footer]]
URL = "/about/hours-directions"
name = "Hours & Directions"
weight = 5
[[menu.footer]]
URL = "donate"
name = "Donate Now"
weight = 4
[[menu.footer]]
URL = "about/contact-connect"
name = "Contact Us"
weight = 3
[[menu.footer]]
URL = "https://bpl.org"
name = "BPL.org"
weight = 9
[[menu.footer]]
URL = "articles"
name = "Articles"
weight = 2
[[menu.footer]]
URL = "event"
name = "Events"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 6
[[menu.main]]
URL = "projects"
name = "Projects"
weight = 5
[[menu.main]]
URL = "research"
name = "Research"
weight = 4
[[menu.main]]
URL = "education"
name = "Education"
weight = 3
[[menu.main]]
URL = "collections"
name = "Collections"
weight = 2
[[menu.main]]
URL = "exhibitions"
name = "Exhibitions"
weight = 1
[params]
address = "Central Library in Copley Square   \n700 Boylston Street   \nBoston, MA 02116 USA"
author = "Leventhal Map & Education Center"
copyright = "All material on this website is licensed under a [Creative Commons BY-ND 4.0 license](https://creativecommons.org/licenses/by-nd/4.0/) unless specified otherwise.\n"
description = "We use maps, geography, and history to explore the connections between places and people in Boston, New England, and beyond. Our collection of a quarter million goegraphic objects, our educational programs, and free exhibitions bring the power of historical geography to everyone."
email = "info@leventhalmap.org"
google_analytics_id = "UA-812961-1"
images = ["https://fedora.digitalcommonwealth.org/fedora/objects/commonwealth:3f463530h/datastreams/thumbnail300/content"]
logo = "images/MapCenter_allwhite.png"
mobile = "+1 617.859.2387"
top_header = true
emailPopup = true
[[params.plugins.css]]
link = "plugins/bootstrap-5.1.3/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.min.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap-5.1.3/js/bootstrap.bundle.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://unpkg.com/@fortawesome/fontawesome-free@6.7.2/js/all.js"
[[params.plugins.js]]
link = "plugins/jump/jump.js"
[params.subscription]
enable = false
[[params.social]]
icon = "fab fa-facebook"
link = "https://facebook.com/bplmaps"
title = "facebook"
[[params.social]]
icon = "fab fa-twitter"
link = "https://twitter.com/bplmaps"
title = "twitter"
[[params.social]]
icon = "fab fa-instagram"
link = "https://instagram.com/bplmaps"
title = "instagram"
[[params.social]]
icon = "fab fa-youtube"
link = "https://www.youtube.com/c/LeventhalMapEducationCenter"
title = "youtube"
[[params.social]]
icon = "fab fa-flickr"
link = "https://www.flickr.com/photos/normanbleventhalmapcenter/"
title = "github"
[[params.social]]
icon = "fab fa-github"
link = "https://github.com/bplmaps"
title = "github"
[[params.social]]
icon = "fab fa-bluesky"
link = "https://bsky.app/profile/bplmaps.bsky.social"
title = "bluesky"
[social]
facebook = "bplmaps"
twitter = "bplmaps"
[params.specialButton]
link = "https://www.leventhalmap.org/about/hours-directions/"
icon = "fas fa-store-alt-slash"
text = "Closed Thursday, November 11"
enabled = false
