[build]
    command = "yarn install && yarn tinacms build && hugo -FD --config config.toml,hugo-config-netlify.toml"
    publish = "public"

[build.environment]
    NODE_VERSION='18'
    TZ='America/New_York'