---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/homepage.yml
  label: Homepage Configuration
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Top-Level Pages
  create: all
  match: "*"
- type: directory
  path: content/education
  label: Education
  create: all
  match: "**/*"
- type: directory
  path: content/research
  label: Research
  create: all
  match: "**/*"
- type: directory
  path: content/exhibitions
  label: Exhibitions
  create: all
  match: "**/*"
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: content/collections
  label: Collections
  create: all
  match: "**/*"
- type: directory
  path: content/event
  label: Event
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.74.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.68.3
