name = "LMEC Neatline"
license = "CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
min_version = "0.60.0"

[original]
  name = "Educenter"
  homepage = "https://themefisher.com/products/education-template/"
